TopicConfigurationResult:
  type: object
  properties:
    topics:
      type: array
      items: string
    newReplicationFactor:
      type: integer
      format: int32
    version:
      type: integer
      format: int32
