TopicConfigurationResult:
  type: object
  required:
    - topics
    - newReplicationFactor
    - version
  properties:
    topics:
      type: array
      items:
        type: string
    newReplicationFactor:
      type: integer
      format: int32
    version:
      type: integer
      format: int32
